### ISSUE TITLE
train.py dies with OutOfMemoryError

### ISSUE THREAD

**Issue by jjdredd** [MaliParag/ScanSSD#3]
The train script dies with OutOfMemoryError in opencv allocation. 
4G RAM, 5G swap, num_workers = 1-4.

How much memory do I need to train this model and how can I optimize the code for memory usage?

**Comment by MaliParag** [comment]
Hi, 

This can be fixed by generating all sub-images before starting the training. And later you may can use earlier version of data loader. 

 Link to old data loader: https://github.com/MaliParag/ScanSSD/blob/7e6d53942b9fa9564fbe6581e2b541ebfa94ced3/data/gtdb.py

I updated data loader in the code because I did not want to generate the sub-images beforehand and I had about 512GB RAM available (although this program does not need that much).

As you only have 4GB available, you should use older version and generate sub-images before training.

**Comment by jjdredd** [comment]
Oh, thanks. So do I just copy that module or does it need some modifications before it can run?

**Comment by jjdredd** [comment]
easy fix via https://github.com/jjdredd/ScanSSD/commit/53739528f802371633226446637c2ff959100316
